name: Smoke Tests

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch: 
    inputs:
      browser:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    env:
      BROWSER: ${{ github.event.inputs.browser || 'chromium' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers 
        run: npx playwright install --with-deps

      - name: Run Playwright Smoke Tests
        run: npx playwright test --grep @smoke --project=${{ env.BROWSER }}

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7